<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TypeSense</AssemblyName>
    <RootNamespace>TypeSense</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\logo.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PinYinConverterCore" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\logo.png" />
    <Resource Include="assets\cursors\grab.cur" />
    <Resource Include="assets\cursors\grabbing.cur" />
    <None Update="assets\logo.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
